import React from "react";
import Grid from "@mui/material/Grid";
import Widget1 from "../Assets/Images/Widget1.png";
import Widget2 from "../Assets/Images/Widget2.png";
import Widget3 from "../Assets/Images/Widget3.png";

function Widget() {
  return (
    <div className="widget">
      <div>
        <Grid container spacing={2} className="widget-margin">
          <Grid item xs container direction="column" spacing={2}>
            <Grid item xs>
              <Grid item>
                <img alt="image" src={Widget1} />
              </Grid>
              <div
                gutterBottom
                variant="subtitle1"
                component="div"
                className="widget-heading "
              >
                Search
              </div>
              <div variant="body2" gutterBottom className="widget-subheading">
                Simply add a keyword or a term related to your business in the
                slogan maker search box. Wait for the magic to happen.
              </div>
            </Grid>
          </Grid>
          <Grid item xs container direction="column" spacing={2}>
            <Grid item xs>
              <Grid item>
                <img alt="image" src={Widget2} />
              </Grid>
              <div
                gutterBottom
                variant="subtitle1"
                component="div"
                className="widget-heading"
              >
                Select
              </div>
              <div variant="body2" gutterBottom className="widget-subheading">
                Choose from thousands of options generated by the slogan maker
                that fit your needs.
              </div>
            </Grid>
          </Grid>
          <Grid item xs container direction="column" spacing={2}>
            <Grid item xs>
              <Grid item>
                <img alt="image" src={Widget3} />
              </Grid>
              <div
                gutterBottom
                variant="subtitle1"
                component="div"
                className="widget-heading"
              >
                Stand out
              </div>
              <div variant="body2" gutterBottom className="widget-subheading">
                Congrats on your new slogan. It's time to win the world!
              </div>
            </Grid>
          </Grid>
        </Grid>
      </div>
    </div>
  );
}

export default Widget;
